name: Database Migration with Flyway

on:
  push:
    branches: 
      - "main"
      - "feature/arinaho/database-setup"
    paths:
      - 'tamagotchi-database/scripts/**'

  workflow_dispatch:

jobs:
  migrate-database:
    name: Run Flyway Migration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Flyway Migration
      run: |
        sudo snap install flyway
        flyway migrate -configFiles=/tamagotchi-database/flyway/flyway.conf
